### ISSUE TITLE
usenix同行邀请

### ISSUE THREAD

**Issue by smallcute123** [NemoYuan2008/MD-ML#1]
Hi，我是东南大学的在读phd，在网站上看到了袁博士的usenix security 2024的论文，想问下是否会去八月份的费城参加会议，如果去的话能否一起同行，因为我是一个人参加该会议，去人生地不熟的美国，想找个同伴一起，如果可以的话真的很感谢！我的邮箱是xiaoyu_cheng@seu.edu.cn

**Comment by NemoYuan2008** [comment]
已回复，谢谢！
